CREATE DATABASE DEVPraticaDapperGeneric;

--INICIO - CRIAR TABELA Cliente
USE [DEVPraticaDapperGeneric]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Cliente](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[DataInclusao] [datetime] NOT NULL,
	[Ativo] [bit] NOT NULL,
	[Nome] [nvarchar](50) NOT NULL,
	[DataNascimento] [datetime] NOT NULL,
 CONSTRAINT [PK_Cliente] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
--FIM - CRIAR TABELA Cliente

--INICIO - CRIAR TABELA Fornecedor
USE [DEVPraticaDapperGeneric]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Fornecedor](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[DataInclusao] [datetime] NOT NULL,
	[Ativo] [bit] NOT NULL,
	[RazaoSocial] [nvarchar](50) NOT NULL,
	[CNPJ] [nvarchar](18) NOT NULL,
 CONSTRAINT [PK_Fornecedor] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
--FIM - CRIAR TABELA Fornecedor

--INICIO - CRIAR TABELA Usuario
USE [DEVPraticaDapperGeneric]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Usuario](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[DataInclusao] [datetime] NOT NULL,
	[Ativo] [bit] NOT NULL,
	[Nome] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NULL,
	[DataNascimento] [datetime] NOT NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
--FIM - CRIAR TABELA Usuario

